### ISSUE TITLE
Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu

### ISSUE THREAD

**Issue by ZiangZheng** [Intelligent-Driving-Laboratory/GOPS#15]
The gops works fine when i using the torch2.1.0+cp But I have encounter the problem when i tried using the cuda and torch1.13.1+cu117 with argument `enable_cuda `  for trainning.

```bash
Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument min in method wrapper_clamp_Tensor)
```

at`GOPS/gops/env/wrapper/scale_action.py`

```
        self.min_action = torch.zeros_like(model.action_lower_bound) + min_action
        self.max_action = torch.zeros_like(model.action_upper_bound) + max_action
        self.action_lower_bound = self.min_action
        self.action_upper_bound = self.max_action

    def action(self, action: torch.Tensor) -> torch.Tensor:
        action = torch.clip(action, self.min_action, self.max_action)
```

It seems that `self.max_action` and `self.min_action`  on the cpu device but the `action` passed is on the cuda.

How could i fix this?

```
Name: torch
Version: 1.13.1+cu117
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /home/zhengziang/miniconda3/envs/gops_gpu/lib/python3.8/site-packages
Requires: typing-extensions
Required-by: gops, pytorch-triton-rocm, torchaudio, torchvision
```

**Comment by yangyujie-jack** [comment]
Thanks for raising this issue. This is a bug in model creation. The device of the model is not specified and is always the default value of `None`, which tells GOPS to create tensors on CPU. We have fixed this by specifying the device according to whether or not GPU is used in model creation (see below).
https://github.com/Intelligent-Driving-Laboratory/GOPS/blob/bba1d1dbf25648d33ac26998f7f16838927c6924/gops/create_pkg/create_env_model.py#L93
