### ISSUE TITLE
Conflicts between dependent packages

### ISSUE THREAD

**Issue by SkyEagle8352** [Intelligent-Driving-Laboratory/GOPS#33]
I'm trying to set up the project environment following the instructions provided. However, I encountered an issue during the environment setup, it seems there are some conflicts between dependent packages.

Detailed info is listed as follows:

(base) c:\RLtest\GOPS>conda env create -f gops_environment.yml
Channels:
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed
Channels:
 - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides ipopt >=3.13,<3.13.1.0a0 needed by cyipopt-1.0.3-py36h050866f_1

Could not solve for environment specs
The following packages are incompatible
├─ cyipopt is installable with the potential options
│  ├─ cyipopt 0.3.0 would require
│  │  ├─ python >=3.6,<3.7.0a0 , which can be installed;
│  │  └─ python_abi 3.6.* *_cp36m, which can be installed;
│  ├─ cyipopt [0.3.0|1.1.0] would require
│  │  ├─ python >=3.7,<3.8.0a0 , which can be installed;
│  │  └─ python_abi 3.7.* *_cp37m, which can be installed;
│  ├─ cyipopt 0.3.0 would require
│  │  └─ ipopt >=3.13.3,<3.13.4.0a0 , which requires
│  │     └─ libflang [<6.0.0.a0 |>=5.0.0,<6.0.0.a0 ] with the potential options
│  │        ├─ libflang 5.0.0 would require
│  │        │  └─ openmp 5.0.0 , which can be installed;
│  │        └─ libflang 5.0.0 would require
│  │           └─ vc 14 , which can be installed;
│  ├─ cyipopt [0.3.0|1.1.0|1.2.0|1.3.0] would require
│  │  ├─ python >=3.9,<3.10.0a0 , which can be installed;
│  │  └─ python_abi 3.9.* *_cp39, which can be installed;
│  ├─ cyipopt [1.0.3|1.1.0] would require
│  │  └─ ipopt >=3.13,<3.13.1.0a0 , which does not exist (perhaps a missing channel);
│  ├─ cyipopt [1.1.0|1.2.0|1.3.0] would require
│  │  ├─ python >=3.10,<3.11.0a0 , which can be installed;
│  │  └─ python_abi 3.10.* *_cp310, which can be installed;
│  ├─ cyipopt [1.1.0|1.2.0|1.3.0] would require
│  │  ├─ python >=3.11,<3.12.0a0 , which can be installed;
│  │  └─ python_abi 3.11.* *_cp311, which can be installed;
│  ├─ cyipopt 1.1.0 would require
│  │  └─ python_abi 3.7 *_pypy37_pp73, which can be installed;
│  ├─ cyipopt [1.1.0|1.2.0] would require
│  │  ├─ ipopt [>=3.13 |>=3.14.10,<3.14.11.0a0 |>=3.14.9,<3.14.10.0a0 ] with the potential options
│  │  │  ├─ ipopt [3.14.10|3.14.11|3.14.12|3.14.13|3.14.14] would require
│  │  │  │  ├─ libflang >=5.0.0,<6.0.0.a0 , which can be installed (as previously explained);
│  │  │  │  ├─ metis >=5.1.1,<5.1.2.0a0 , which requires
│  │  │  │  │  └─ vc >=14.2,<15 , which conflicts with any installable versions previously reported;
│  │  │  │  ├─ mumps-seq >=5.6.2,<5.6.3.0a0 , which requires
│  │  │  │  │  └─ vc >=14.2,<15 , which conflicts with any installable versions previously reported;
│  │  │  │  └─ vc >=14.2,<15 , which conflicts with any installable versions previously reported;
│  │  │  └─ ipopt [3.13.3|3.13.4|...|3.14.9], which can be installed (as previously explained);
│  │  ├─ python_abi 3.8 *_pypy38_pp73, which can be installed;
│  │  └─ vc >=14.2,<15 , which conflicts with any installable versions previously reported;
│  ├─ cyipopt [1.1.0|1.2.0|1.3.0] would require
│  │  ├─ ipopt [>=3.13 |>=3.14.10,<3.14.11.0a0 |...|>=3.14.9,<3.14.10.0a0 ] with the potential options
│  │  │  ├─ ipopt [3.14.10|3.14.11|3.14.12|3.14.13|3.14.14], which cannot be installed (as previously explained);
│  │  │  └─ ipopt [3.13.3|3.13.4|...|3.14.9], which can be installed (as previously explained);
│  │  └─ vc >=14.2,<15 , which conflicts with any installable versions previously reported;
│  ├─ cyipopt [1.1.0|1.2.0] would require
│  │  └─ python_abi 3.9 *_pypy39_pp73, which can be installed;
│  ├─ cyipopt 1.2.0 would require
│  │  ├─ ipopt [>=3.14.11,<3.14.12.0a0 |>=3.14.12,<3.14.13.0a0 ], which cannot be installed (as previously explained);
│  │  └─ pypy3.8 >=7.3.11  with the potential options
│  │     ├─ pypy3.8 7.3.11 would require
│  │     │  ├─ libzlib >=1.2.13,<1.3.0a0 , which requires
│  │     │  │  └─ vc >=14.2,<15 , which conflicts with any installable versions previously reported;
│  │     │  └─ openssl [>=3.1.0,<4.0a0 |>=3.1.2,<4.0a0 |>=3.1.3,<4.0a0 ], which requires
│  │     │     └─ vc >=14.2,<15 , which conflicts with any installable versions previously reported;
│  │     └─ pypy3.8 7.3.11, which can be installed;
│  ├─ cyipopt 1.2.0 would require
│  │  └─ pypy3.9 >=7.3.11 , which can be installed;
│  └─ cyipopt 1.3.0 would require
│     └─ python_abi 3.12.* *_cp312, which can be installed;
├─ llvm-openmp <16  is not installable because there are no viable options
│  ├─ llvm-openmp 12.0.0 would require
│  │  └─ openmp 12.0.0|12.0.0.* , which conflicts with any installable versions previously reported;
│  ├─ llvm-openmp 10.0.0 would require
│  │  └─ openmp 10.0.0|10.0.0.* , which conflicts with any installable versions previously reported;
│  ├─ llvm-openmp 10.0.1 would require
│  │  └─ openmp 10.0.1|10.0.1.* , which conflicts with any installable versions previously reported;
│  ├─ llvm-openmp 11.0.0 would require
│  │  └─ openmp 11.0.0|11.0.0.* , which conflicts with any installable versions previously reported;
│  ├─ llvm-openmp 11.0.1 would require
│  │  └─ openmp 11.0.1|11.0.1.* , which conflicts with any installable versions previously reported;
│  ├─ llvm-openmp 11.1.0 would require
│  │  └─ openmp 11.1.0|11.1.0.* , which conflicts with any installable versions previously reported;
│  ├─ llvm-openmp 12.0.1 would require
│  │  └─ openmp 12.0.1|12.0.1.* , which conflicts with any installable versions previously reported;
│  ├─ llvm-openmp 13.0.1 would require
│  │  └─ openmp 13.0.1|13.0.1.* , which conflicts with any installable versions previously reported;
│  ├─ llvm-openmp 14.0.0 would require
│  │  └─ openmp 14.0.0|14.0.0.* , which conflicts with any installable versions previously reported;
│  ├─ llvm-openmp 14.0.2 would require
│  │  └─ openmp 14.0.2|14.0.2.* , which conflicts with any installable versions previously reported;
│  ├─ llvm-openmp 14.0.3 would require
│  │  └─ openmp 14.0.3|14.0.3.* , which conflicts with any installable versions previously reported;
│  ├─ llvm-openmp 14.0.4 would require
│  │  └─ openmp 14.0.4|14.0.4.* , which conflicts with any installable versions previously reported;
│  ├─ llvm-openmp 14.0.6 would require
│  │  ├─ openmp 14.0.6|14.0.6.* , which conflicts with any installable versions previously reported;
│  │  └─ vc [>=14.2,<15 |>=14.2,<15.0a0 ], which conflicts with any installable versions previously reported;
│  ├─ llvm-openmp 15.0.4 would require
│  │  ├─ openmp 15.0.4|15.0.4.* , which conflicts with any installable versions previously reported;
│  │  └─ vc >=14.2,<15 , which conflicts with any installable versions previously reported;
│  ├─ llvm-openmp 15.0.5 would require
│  │  ├─ openmp 15.0.5|15.0.5.* , which conflicts with any installable versions previously reported;
│  │  └─ vc >=14.2,<15 , which conflicts with any installable versions previously reported;
│  ├─ llvm-openmp 8.0.0 would require
│  │  └─ openmp 8.0.0|8.0.0.* , which conflicts with any installable versions previously reported;
│  ├─ llvm-openmp 8.0.1 would require
│  │  └─ openmp 8.0.1|8.0.1.* , which conflicts with any installable versions previously reported;
│  ├─ llvm-openmp 9.0.0 would require
│  │  └─ openmp 9.0.0|9.0.0.* , which conflicts with any installable versions previously reported;
│  ├─ llvm-openmp 9.0.1 would require
│  │  └─ openmp 9.0.1|9.0.1.* , which conflicts with any installable versions previously reported;
│  ├─ llvm-openmp 15.0.6 would require
│  │  ├─ openmp 15.0.6|15.0.6.* , which conflicts with any installable versions previously reported;
│  │  └─ vc >=14.2,<15 , which conflicts with any installable versions previously reported;
│  └─ llvm-openmp 15.0.7 would require
│     ├─ openmp 15.0.7|15.0.7.* , which conflicts with any installable versions previously reported;
│     └─ vc >=14.2,<15 , which conflicts with any installable versions previously reported;
├─ python 3.8**  is not installable because there are no viable options
│  ├─ python [3.8.0|3.8.1|...|3.8.8] conflicts with any installable versions previously reported;
│  ├─ python [3.8.0|3.8.1] would require
│  │  └─ python_abi * *_cp38, which conflicts with any installable versions previously reported;
│  ├─ python [3.8.14|3.8.15|...|3.8.19] would require
│  │  └─ libzlib >=1.2.13,<1.3.0a0 , which cannot be installed (as previously explained);
│  └─ python 3.8.16 would require
│     └─ pypy3.8 7.3.11.*  with the potential options
│        ├─ pypy3.8 7.3.11, which cannot be installed (as previously explained);
│        └─ pypy3.8 7.3.11, which can be installed;
└─ pytorch >=1.13.0  is installable with the potential options
   ├─ pytorch 2.2.0 would require
   │  └─ vc >=14.2,<15.0a0 , which conflicts with any installable versions previously reported;
   ├─ pytorch [2.0.1|2.1.0|2.2.0] would require
   │  └─ python >=3.10,<3.11.0a0 , which can be installed;
   ├─ pytorch [2.0.1|2.1.0|2.2.0] would require
   │  └─ python >=3.11,<3.12.0a0 , which can be installed;
   ├─ pytorch [2.0.1|2.1.0] would require
   │  ├─ python >=3.8,<3.9.0a0  but there are no viable options
   │  │  ├─ python [3.8.0|3.8.1|...|3.8.8] conflicts with any installable versions previously reported;
   │  │  ├─ python [3.8.0|3.8.1], which cannot be installed (as previously explained);
   │  │  ├─ python [3.8.14|3.8.15|...|3.8.19], which cannot be installed (as previously explained);
   │  │  └─ python 3.8.16, which cannot be installed (as previously explained);
   │  └─ vc >=14.2,<15.0a0 , which conflicts with any installable versions previously reported;
   ├─ pytorch [2.0.1|2.1.0|2.2.0] would require
   │  └─ python >=3.9,<3.10.0a0 , which can be installed;
   └─ pytorch 2.2.0 would require
      └─ python >=3.12,<3.13.0a0 , which can be installed.

**Comment by zhengzl18** [comment]
This is due to the different dependencies of `ipopt` package on linux and windows, the latter of which depends on `openmp 5.0.0`, conflicting with `llvm-openmp<16` in `gops_environment.yml`. We fix this in #34 by deviding `gops_environment.yml` into two files, for linux and windows respectively.
